import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {nextUnseenLinks,explicitArticleDate} from "./discovery.mjs";
import {robotsPolicy} from "./robots.mjs";
import {extractSaplMateria} from "./sapl.mjs";
const SB=Deno.env.get("SUPABASE_URL")!,KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const H={apikey:KEY,Authorization:`Bearer ${KEY}`,"Content-Type":"application/json"};
const rpc=async(n:string,a:any={})=>{const r=await fetch(`${SB}/rest/v1/rpc/${n}`,{method:"POST",headers:H,body:JSON.stringify(a)});if(!r.ok)throw new Error(`db_${r.status}:`+(await r.text()).slice(0,500));const t=await r.text();return t?JSON.parse(t):null};
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const entity=(s:string)=>s.replace(/<!\[CDATA\[|\]\]>/g,"").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(+n));
const clean=(s:string)=>entity(s.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi," ").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim());
const tag=(s:string,n:string)=>entity(s.match(new RegExp(`<${n}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${n}>`,"i"))?.[1]||"").trim();
const titleHtml=(h:string)=>clean(h.match(/<meta[^>]+(?:property|name)=["'](?:og:title|twitter:title)["'][^>]+content=["']([^"']+)/i)?.[1]||h.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||"Documento sem título").slice(0,500);
const dateHtml=explicitArticleDate;
const isoDate=(s:string)=>{const d=new Date(s);return Number.isNaN(d.valueOf())?null:d.toISOString().slice(0,10)};
const sha=async(s:string)=>[...new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s)))].map(x=>x.toString(16).padStart(2,"0")).join("");
const normUrl=(raw:string)=>{const u=new URL(raw);for(const k of [...u.searchParams.keys()])if(k.startsWith("utm_")||["fbclid","gclid"].includes(k))u.searchParams.delete(k);u.hash="";u.pathname=u.pathname.replace(/\/amp\/?$/i,"").replace(/\/+$/,"")||"/";return u.toString()};
const normTitle=(s:string)=>s.toLocaleLowerCase("pt-BR").replace(/\s+/g," ").replace(/[.!?;:,]+$/,"").trim();
const policies=new Map<string,any>(),lastRequest=new Map<string,number>(),delays=new Map<string,number>();
async function get(url:string){const domain=new URL(url).origin,wait=(lastRequest.get(domain)||0)+(delays.get(domain)||1000)-Date.now();if(wait>0)await sleep(wait);lastRequest.set(domain,Date.now());const c=new AbortController(),tm=setTimeout(()=>c.abort(),18000);try{const r=await fetch(url,{redirect:"follow",signal:c.signal,headers:{"User-Agent":"RadarTomeNota/1.1 (+https://radar-tome-nota.onrender.com)","Accept":"text/html,application/rss+xml,application/xml;q=0.9"}});if(!r.ok)throw new Error(`http_${r.status}`);return await r.text()}finally{clearTimeout(tm)}}
async function robotsOK(raw:string){const u=new URL(raw);if(!policies.has(u.origin)){let txt="";try{txt=await get(u.origin+"/robots.txt")}catch(e){if(!/^Error: http_(404|410)$/.test(String(e)))throw new Error("robots_indisponivel")}const p=robotsPolicy(txt);policies.set(u.origin,p);delays.set(u.origin,p.delay*1000)}return policies.get(u.origin).allowed(raw)}
function rssItems(xml:string,max:number){return [...xml.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].slice(0,max).map(m=>{const x=m[1],t=clean(tag(x,"title")),u=clean(tag(x,"link")),desc=clean(tag(x,"description")).slice(0,2500),pub=tag(x,"pubDate"),source=clean(tag(x,"source"));return{title:t,url:u,date:isoDate(pub),evidence:[t,desc,source?("Fonte indicada no feed: "+source):""].filter(Boolean).join(". ")}}).filter(x=>x.title&&/^https?:\/\//.test(x.url)&&x.evidence.length>30)}
function htmlLinks(html:string,base:string,inc:string[],max:number){const out:string[]=[];for(const m of html.matchAll(/<a\b[^>]*href=["']([^"'#]+)["']/gi)){try{const u=new URL(entity(m[1]),base);if(u.origin===new URL(base).origin&&inc.some(x=>(u.pathname+u.search).includes(x))&&(!base.includes("sapl.saogoncalodoamarante.ce.leg.br")||/^\/materia\/\d+\/?$/.test(u.pathname))&&!out.includes(u.toString()))out.push(u.toString())}catch{}if(out.length>=max)break}return out}
async function ingest(s:any,x:any){const u=normUrl(x.url),t=x.title.slice(0,500),nt=normTitle(t),e=x.evidence.slice(0,12000),hc=await sha(e),ck=await sha(u+"\n"+nt+"\n"+(x.date||"")),rule=s.regra_extracao||{};return rpc("tn_ingerir_candidato_automatico",{redacao_id:s.redacao_id,fonte_id:s.id,url_original:x.url,url_normalizada:u,titulo_original:t,titulo_normalizado:nt,data_documento:x.date,evidencia:e,hash_conteudo:hc,chave_canonica:ck,localidade:rule.cidade||"A confirmar",categoria:rule.categoria||"Geral"})}
async function source(s:any){const start=Date.now(),rule=s.regra_extracao||{};let raw=0,created=0,dupes=0,errors=0;try{if(!(await robotsOK(s.url)))throw new Error("robots_bloqueou");const body=await get(s.url);let items:any[]=[];if(s.tipo==="rss")items=rssItems(body,Math.min(+(rule.max_itens||8),12));else{const candidates=htmlLinks(body,s.url,rule.link_include||[],rule.parser==="sapl_materia"?30:Math.min(+(rule.max_itens||6),8));const known=rule.parser==="sapl_materia"?await rpc("tn_coletor_urls_conhecidas",{fonte_id:s.id}):[];const links=rule.parser==="sapl_materia"?nextUnseenLinks(candidates,known,1):candidates;for(const u of links){await sleep(800);try{if(!(await robotsOK(u)))continue;const h=await get(u),e=clean(h).slice(0,12000);if(rule.parser==="sapl_materia")items.push(extractSaplMateria(h,u));else if(e.length>=80)items.push({title:titleHtml(h),url:u,date:dateHtml(h),evidence:e})}catch{errors++}}}items=items.filter((x:any)=>!(x.sourceDate||x.date)||Date.parse((x.sourceDate||x.date)+"T00:00:00Z")>=Date.now()-7*86400000);for(const x of items){raw++;try{const r=await ingest(s,x);r?.novo?created++:dupes++}catch{errors++}}if(errors>0)throw new Error("falha_parcial_documentos");const now=new Date().toISOString();await rpc("tn_coletor_atualizar_fonte",{fonte_id:s.id,alteracoes:{ultima_varredura:now,ultimo_sucesso:now,proxima_varredura:new Date(Date.now()+s.intervalo_segundos*1000).toISOString(),ultimo_erro_codigo:"",ultimo_erro_texto:"",falhas_consecutivas:0,tentativas_backoff:0,estado_circuito:"fechado",ultima_latencia_ms:Date.now()-start}});await rpc("tn_coletor_registrar_coleta",{dados:{redacao_id:s.redacao_id,fonte_id:s.id,inicio:new Date(start).toISOString(),fim:now,status:"concluida",documentos_lidos:raw,candidatos_criados:created,duplicados:dupes,itens_brutos:raw,itens_novos:created,erros:errors,latencia_ms:Date.now()-start}});return{fonte:s.nome,brutos:raw,novos:created,duplicados:dupes,erros:errors}}catch(e){await rpc("tn_coletor_registrar_coleta",{dados:{redacao_id:s.redacao_id,fonte_id:s.id,inicio:new Date(start).toISOString(),fim:new Date().toISOString(),status:"falhou",documentos_lidos:raw,candidatos_criados:created,duplicados:dupes,erros:errors+1,latencia_ms:Date.now()-start}});const n=+(s.falhas_consecutivas||0)+1,open=n>=3,mins=[5,15,45,120,240][Math.min(n-1,4)];await rpc("tn_coletor_atualizar_fonte",{fonte_id:s.id,alteracoes:{ultima_varredura:new Date().toISOString(),proxima_varredura:new Date(Date.now()+mins*60000).toISOString(),ultimo_erro_codigo:String(e).slice(0,300),ultimo_erro_texto:"Falha sanitizada na coleta automática.",falhas_consecutivas:n,tentativas_backoff:n,estado_circuito:open?"aberto":"fechado",circuito_aberto_em:open?new Date().toISOString():"",cooldown_ate:open?new Date(Date.now()+240*60000).toISOString():"",ultima_falha_em:new Date().toISOString(),ultima_latencia_ms:Date.now()-start}});return{fonte:s.nome,erro:true,circuito:open?"aberto":"fechado"}}}
Deno.serve(async req=>{if(!(await rpc("tn_coletor_autorizar",{chave:req.headers.get("X-Radar-Collector")})))return new Response("Acesso interno obrigatório",{status:403});if(req.method!=="POST")return new Response("Método não permitido",{status:405});try{const all=await rpc("tn_coletor_fontes_pendentes"),now=Date.now(),eligible=all.filter((s:any)=>(!s.proxima_varredura||Date.parse(s.proxima_varredura)<=now)&&(s.estado_circuito!=="aberto"||!s.cooldown_ate||Date.parse(s.cooldown_ate)<=now)),due=eligible.some((s:any)=>s.regra_extracao?.parser==="sapl_materia")?eligible.filter((s:any)=>s.regra_extracao?.parser==="sapl_materia").slice(0,1):eligible.slice(0,6),results=[];for(const s of due)results.push(await source(s));return Response.json({ok:true,fontes_processadas:due.length,resultados:results})}catch(e){console.error(JSON.stringify({evento:"rodada_falhou",codigo:String(e).slice(0,120)}));return Response.json({ok:false,erro:"Falha controlada na rodada."},{status:500})}});
