import React,{useState} from 'react';
const cities=['São Gonçalo do Amarante','Pecém','Taíba','Siupé','Paracuru','Paraipaba','Caucaia'];
const isInstagram=url=>{try{return /(^|\.)instagram\.com$/.test(new URL(url).hostname)}catch{return false}};
export default function Dashboard({queue,busy,refresh,open}){
 const [city,setCity]=useState(cities[0]),[term,setTerm]=useState('');
 const rows=queue.filter(x=>x.pauta.localidade?.toLocaleLowerCase('pt-BR').includes(city.toLocaleLowerCase('pt-BR')));
 const social=rows.filter(x=>isInstagram(x.pauta.url_fonte));
 const categories=Object.entries(rows.reduce((a,x)=>(a[x.pauta.categoria]=(a[x.pauta.categoria]||0)+1,a),{})).sort((a,b)=>b[1]-a[1]);
 const search=`${term} "${city}" Ceará`;
 return <section><div className="queue-head"><div><h2>Painel de buscas</h2><p className="muted">Dados da fila compartilhada, atualizados ao abrir ou clicar em Atualizar. Até 250 pautas.</p></div><button disabled={busy} onClick={refresh}>Atualizar painel</button></div>
 <div className="dashboard-stats">{[['Pautas na fila',queue.length],['Em apuração',queue.filter(x=>x.pauta.status==='apurar').length],['Com fonte Instagram',queue.filter(x=>isInstagram(x.pauta.url_fonte)).length],['Pacotes conferidos',queue.filter(x=>x.pauta.conferida).length]].map(([label,n])=><div className="panel" key={label}><strong className="stat-number">{n}</strong><p>{label}</p></div>)}</div>
 <div className="dashboard-columns"><section className="panel"><p className="eyebrow">01 / DESCOBERTA</p><h2>Pesquisar na região</h2><label>Cidade ou distrito<select value={city} onChange={e=>setCity(e.target.value)}>{cities.map(c=><option key={c}>{c}</option>)}</select></label><label>Assunto<input value={term} onChange={e=>setTerm(e.target.value)} placeholder="Ex.: abastecimento de água"/></label><div className="actions"><a target="_blank" rel="noopener noreferrer" href={'https://www.google.com/search?q='+encodeURIComponent('site:instagram.com '+search)}>Buscar posts públicos ↗</a><a target="_blank" rel="noopener noreferrer" href={'https://www.google.com/search?q='+encodeURIComponent(search)}>Buscar fontes na web ↗</a></div><p className="footnote">As buscas abrem fora do Radar e não importam resultados. O Google não cobre todo o Instagram. Cadastre a pauta e registre o link e a evidência para revisão.</p></section>
 <section className="panel"><p className="eyebrow">02 / SINAIS LOCAIS</p><h2>O que chegou à redação</h2><p>{rows.length} registros em {city}. {social.length} com fonte Instagram.</p>{categories.map(([c,n])=><p key={c}><strong>{c}</strong> · {n} pautas</p>)}{!rows.length&&<p>Nenhum registro nesta localidade.</p>}<p className="footnote">Frequência na fila não comprova assunto em alta na cidade. Tendência automática ainda não medida: faltam séries de observações, crescimento e fontes independentes.</p></section>
 <section className="panel"><p className="eyebrow">03 / HEADLINES</p><h2>Atenção com responsabilidade</h2><p>Abra uma pauta, salve a evidência e registre a conferência humana. Depois peça três sugestões de título com justificativas editoriais.</p><p className="footnote">Foco em clareza, utilidade e impacto local. Sem prometer viralização. A IA não altera nem aprova o texto.</p></section></div>
 <section className="panel"><h2>Pautas para investigar · {city}</h2>{rows.map(item=><button className="item" key={item.pauta.id} onClick={()=>open(item)}><h3>{item.pauta.titulo}</h3><small>{item.pauta.categoria} · Documento: {item.pauta.data_documento||'não identificado'} · Fato: {item.pauta.data_fato||'não identificado'}</small></button>)}{!rows.length&&<p>Use “Adicionar pauta” para registrar a primeira descoberta com sua fonte.</p>}</section>
 </section>;
}
