import React,{useState,useEffect,useRef,useMemo} from 'react';
import {dashboardData,normalize,safeSource} from './dashboard-model.mjs';
const time=v=>v?new Date(v).toLocaleString('pt-BR',{timeZone:'America/Fortaleza',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'Ainda sem registro';
const labels={apurar:'Em apuração',revisar:'Revisar texto',aprovada:'Aprovada',descartada:'Descartada'};
function Icon(){return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="4"/><path d="M12 12 20 4"/></svg>}
export default function Dashboard({request,open,roomId,userId}){
 const [raw,setRaw]=useState(null),[error,setError]=useState(''),[refreshing,setRefreshing]=useState(false),[reload,setReload]=useState(0),[section,setSection]=useState('overview');
 const [city,setCity]=useState('Todas'),[query,setQuery]=useState(''),[filter,setFilter]=useState('work'),[opening,setOpening]=useState(null);
 const visitKey=`radar-seen:${userId}:${roomId}`;
 const [cutoff,setCutoff]=useState(()=>{try{return localStorage.getItem(visitKey)||null}catch{return null}});
 const req=useRef(request);req.current=request;
 useEffect(()=>{let active=true,timer;async function load(){setRefreshing(true);try{const next=await req.current('/dashboard');if(active){setRaw(next);setError('')}}catch(e){if(active)setError(e.message)}finally{if(active){setRefreshing(false);timer=setTimeout(load,30000)}}}load();return()=>{active=false;clearTimeout(timer)}},[reload,roomId]);
 const data=useMemo(()=>raw?dashboardData(raw,Date.parse(raw.servidor_em)):null,[raw]);
 const isNew=p=>cutoff&&Date.parse(p.criada_em)>Date.parse(cutoff);
 const rows=(data?.pautas||[]).filter(p=>(city==='Todas'||normalize(p.localidade).includes(normalize(city)))&&normalize(p.titulo+' '+p.categoria+' '+p.localidade).includes(normalize(query))&&(filter==='all'||filter==='work'&&p.signals.workable||filter==='new'&&isNew(p)||filter==='pending'&&p.signals.pending.length&&!['aprovada','descartada'].includes(p.status)||filter==='archive'&&(p.signals.old||p.signals.generic||['aprovada','descartada'].includes(p.status)))).sort((a,b)=>b.signals.points-a.signals.points||String(b.criada_em).localeCompare(String(a.criada_em)));
 const failures=data?.sources.filter(f=>['error','warning'].includes(f.health.state))||[];
 function seen(){if(!raw)return;setCutoff(raw.servidor_em);try{localStorage.setItem(visitKey,raw.servidor_em)}catch{setError('A marcação vale apenas nesta sessão; o navegador não permitiu salvá-la.')}}
 async function openItem(id){setOpening(id);try{open(await req.current('/pautas/'+id))}catch(e){setError(e.message)}finally{setOpening(null)}}
 function showQueue(next,local='Todas'){setSection('queue');setFilter(next);setCity(local);setQuery('')}
 const card=p=><article className="story-card" key={p.id}><div className="story-meta"><span>{p.localidade}</span>{isNew(p)&&<b className="new-label">NOVA NA FILA</b>}<span>{labels[p.status]}</span></div><h3>{p.titulo}</h3><div className="story-facts"><span>Documento <b>{p.data_documento||'a conferir'}</b></span><span>Fato <b>{p.data_fato||'a conferir'}</b></span></div><p className="story-source">{p.fonte||'Fonte não identificada'} · {p.agente||'Sem atribuição registrada'}</p><div className="story-bottom"><span className="priority-number">{p.signals.points}<small>/100 · prioridade</small></span><button disabled={opening!==null} className="primary" onClick={()=>openItem(p.id)}>{opening===p.id?'Abrindo…':'Abrir apuração →'}</button></div><details><summary>Por que esta prioridade?</summary><ul>{p.signals.reasons.map(s=><li key={s}>{s}</li>)}</ul><p>Ordem de trabalho por regras; não mede veracidade ou chance de viralizar.</p>{p.signals.pending.map(s=><p className="check-gap" key={s}>{s}</p>)}<p className="footnote">Entrada: {time(p.criada_em)} · {p.codigo} v{p.versao}</p>{safeSource(p.url_fonte)&&<a href={safeSource(p.url_fonte)} target="_blank" rel="noopener noreferrer">Abrir fonte original ↗</a>}</details></article>;
 return <div className="operations">
  <section className="operations-hero"><div><p className="eyebrow">TOME NOTA NEWS / INTELIGÊNCIA EDITORIAL</p><h1>Sua região,<br/>em pauta.</h1><p>O que chegou. O que merece atenção.<br/>O que precisa ser conferido.</p></div><div className="hero-watch"><Icon/><strong>{raw?time(raw.servidor_em):'Conectando à redação'}</strong><span>{error?'Atualização interrompida':refreshing?'Atualizando dados…':'Última consulta ao servidor'}</span><button onClick={()=>setReload(n=>n+1)} disabled={refreshing}>Atualizar agora</button></div></section>
  {error&&<div className="feedback" role="alert">{error} {raw?'Os dados anteriores foram mantidos.':'Não foi possível obter o painel.'}<button onClick={()=>setReload(n=>n+1)} disabled={refreshing}>Tentar novamente</button></div>}
  {!data?<div className="panel dashboard-loading" role="status"><Icon/><h2>{error?'Dados indisponíveis':'Carregando a operação'}</h2><p>Consultando pautas, fontes e histórico de coleta.</p></div>:<>
  <div className="operation-metrics">
   <button onClick={()=>showQueue('all')}><small>FILA COMPARTILHADA</small><strong>{data.total_pautas}</strong><span>registros no servidor →</span></button>
   <button onClick={()=>showQueue('work')}><small>PARA TRABALHAR</small><strong>{data.work.length}</strong><span>candidatos em apuração →</span></button>
   <button onClick={()=>showQueue('pending')}><small>EXIGEM CONFERÊNCIA</small><strong>{data.pending.length}</strong><span>datas, fonte ou evidência →</span></button>
   <button onClick={()=>setSection('sources')}><small>ATENÇÃO À COLETA</small><strong>{failures.length}</strong><span>fontes com falha ou lacuna →</span></button>
  </div>
  <div className="operation-nav" role="group" aria-label="Seções do dashboard">{[['overview','Visão do dia'],['queue','Mesa de pautas'],['sources','Saúde das fontes'],['agents','Agentes']].map(([id,label])=><button aria-pressed={section===id} className={section===id?'active':''} key={id} onClick={()=>setSection(id)}>{label}</button>)}</div>
  {section==='overview'&&<>
   <div className="operation-brief"><div><p className="eyebrow">LEITURA DA OPERAÇÃO</p><h2>{data.recent?`${data.recent} entradas nas últimas 24 horas.`:'Nenhuma entrada nas últimas 24 horas.'}</h2><p>{data.work.length} candidatos para trabalhar. {data.pautas.filter(p=>p.signals.old).length} documentos antigos separados da seleção principal. Entrada recente na fila não comprova fato novo.</p></div><button onClick={()=>showQueue('pending')}>Resolver pendências →</button></div>
   <div className="overview-columns"><section className="panel"><p className="eyebrow">COBERTURA TERRITORIAL</p><h2>Onde estão as pautas</h2><p className="footnote">Localidade registrada na pauta; menções no texto não mudam a cidade automaticamente.</p><div className="city-map">{data.cityCounts.map(c=><button key={c.city} onClick={()=>showQueue('all',c.city)}><span>{c.city}</span><meter min="0" max={Math.max(1,...data.cityCounts.map(x=>x.total))} value={c.total} aria-label={`${c.total} pautas em ${c.city}`}/><strong>{c.total}</strong></button>)}</div></section><section className="panel collection-pulse"><p className="eyebrow">PULSO DA COLETA / 24H</p><h2>A operação por trás da fila</h2><div><strong>{data.coletas_24h.length}</strong><span>rodadas registradas por fonte</span></div><div><strong>{data.coletas_24h.reduce((n,c)=>n+c.candidatos_criados,0)}</strong><span>candidatos criados</span></div><div><strong>{data.coletas_24h.reduce((n,c)=>n+c.duplicados,0)}</strong><span>duplicatas evitadas</span></div><button onClick={()=>setSection('sources')}>Ver fontes e próximas buscas →</button></section></div>
   <div className="section-line"><div><p className="eyebrow">SELEÇÃO DE TRABALHO</p><h2>Comece por estas pautas</h2></div><button onClick={()=>showQueue('work')}>Ver mesa completa →</button></div>
   <div className="story-grid">{data.work.slice().sort((a,b)=>b.signals.points-a.signals.points||String(b.criada_em).localeCompare(String(a.criada_em))).slice(0,3).map(card)}</div>{!data.work.length&&<div className="panel empty"><h3>Nenhum candidato elegível neste momento.</h3><p>A coleta continua. Consulte pendências ou arquivo sem apresentar documentos antigos como novidade.</p></div>}
   <div className="coverage-limits"><strong>Repercussão com evidência</strong><p>Instagram e WhatsApp ainda não conectados. Tendências não são calculadas sem volume, autores e comparação histórica suficientes. O painel usa regras de prioridade, não análise Gemini.</p></div>
  </>}
  {section==='queue'&&<section><div className="queue-toolbar"><label className="search-box"><Icon/><input aria-label="Buscar na mesa" placeholder="Buscar assunto, cidade ou categoria" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Localidade<select value={city} onChange={e=>setCity(e.target.value)}><option>Todas</option>{data.cityCounts.map(c=><option key={c.city}>{c.city}</option>)}</select></label><label>Exibir<select value={filter} onChange={e=>setFilter(e.target.value)}>{[['work','Para trabalhar'],['new','Novas neste navegador'],['pending','Com pendências'],['archive','Arquivo / encerradas'],['all','Todas']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></div><div className="section-line"><p>{rows.length} registros encontrados · ordem de prioridade</p><button onClick={seen}>Marcar entradas como vistas</button></div>{!cutoff&&<p className="footnote">Primeira visita registrada neste navegador: marque as entradas como vistas para destacar as próximas.</p>}<div className="story-grid">{rows.map(card)}</div>{!rows.length&&<div className="panel empty"><h3>Nenhuma pauta atende a estes filtros.</h3><button onClick={()=>showQueue('all')}>Limpar filtros e ver todas</button></div>}</section>}
  {section==='sources'&&<section className="sources-panel"><div className="section-line"><div><h2>Saúde e cobertura das fontes</h2><p>Sites que respondem sem encontrar documentos aparecem como lacuna, não como coleta produtiva.</p></div></div>{data.sources.map(f=><article className="source-row" key={f.id}><span className={'health-dot '+f.health.state}/><div><h3>{f.nome}</h3><strong className={'health-label '+f.health.state}>{f.health.label}</strong><p>{f.health.detail}</p>{safeSource(f.url)&&<a href={safeSource(f.url)} target="_blank" rel="noopener noreferrer">Consultar site ↗</a>}</div><dl><dt>Último sucesso</dt><dd>{time(f.ultimo_sucesso)}</dd><dt>Próxima verificação elegível</dt><dd>{f.ativa?time(f.proxima_varredura):'Coleta desativada'}</dd></dl></article>)}<p className="footnote">O agendador verifica fontes a cada 15 minutos. Fontes lentas e falhas podem adiar o processamento; o horário indicado não garante conclusão.</p></section>}
  {section==='agents'&&<section><div className="section-line"><div><h2>Especialidades da redação</h2><p>Dez agentes de triagem por regras. Atribuições reais, sem simular atividade de IA.</p></div></div><div className="agent-grid">{data.agentes.map(a=><article className="panel agent-card" key={a.id}><span className="agent-number">{String(a.numero).padStart(2,'0')}</span><h3>{a.nome}</h3><p>{a.instrucao}</p><strong>{a.atribuicoes} candidatos atribuídos</strong><p className="footnote">Última atribuição: {time(a.ultima_atribuicao)}<br/>{a.ativo?'Triagem habilitada':'Pausado'}</p></article>)}</div></section>}
  <p className="footnote operation-footer">Atualização automática a cada 30 segundos enquanto este painel está aberto. Coleta no servidor continua com o navegador fechado. Exibidos {data.pautas.length} de {data.total_pautas} registros; limite de 500 na análise.</p>
 </>}
 </div>;
}
