import React,{useEffect,useMemo,useState} from 'react';

const categories=['Prioridade','Faculdade','Adapta','Rotina','Organização e Extras','Compromissos','Saúde'];
const fronts={grupo:'Grupo Tome Nota',agencia:'Agência',jornal:'Tome Nota News',marca_pessoal:'Marca pessoal'};
const ptDate=value=>value?new Date(value+'T12:00:00').toLocaleDateString('pt-BR'):'Sem prazo';

export default function Management({request,run,busy,canWrite,setMessage}){
 const [data,setData]=useState(null),[form,setForm]=useState({titulo:'',categoria:'Prioridade',frente:'grupo',cliente:'',prazo:'',prioridade:true}),[note,setNote]=useState('');
 const [loadError,setLoadError]=useState(''),[loaded,setLoaded]=useState(false),[decision,setDecision]=useState(null),[reason,setReason]=useState('');
 const load=async()=>{setLoadError('');try{setData(await request('/gestao'));setLoaded(true)}catch(error){setLoadError(error.message);throw error}};
 useEffect(()=>{run(load)},[]);
 const tasks=data?.tarefas||[],today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Fortaleza',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const briefing=useMemo(()=>tasks.filter(t=>t.status==='pendente').sort((a,b)=>Number(b.prioridade)-Number(a.prioridade)||String(a.prazo||'9999').localeCompare(String(b.prazo||'9999'))).slice(0,3),[tasks]);
 async function create(e){e.preventDefault();if(!note.trim())return setMessage('Explique por que esta tarefa entrou na rotina.');await run(async()=>{await request('/gestao/tarefas',{dados:form,nota:note});setForm({titulo:'',categoria:'Prioridade',frente:'grupo',cliente:'',prazo:'',prioridade:true});setNote('');await load();setMessage('Tarefa compartilhada registrada.')})}
 function change(task,action){setDecision({task,action});setReason('')}
 async function saveDecision(e){e.preventDefault();if(reason.trim().length<3)return;await run(async()=>{await request(`/gestao/tarefas/${decision.task.id}/${decision.action}`,{nota:reason});setDecision(null);await load();setMessage('Decisão registrada com autor, horário e snapshot.')})}
 if(!loaded)return <section className="panel" role="status"><h2>{loadError?'Não foi possível carregar a Gestão':'Carregando a Gestão…'}</h2><p>{loadError||'Consultando tarefas no servidor. Isso não indica ausência de tarefas.'}</p>{loadError&&<button disabled={busy} onClick={()=>run(load)}>Tentar carregar novamente</button>}</section>;
 return <div className="management">
  {loadError&&<div role="alert" className="feedback">{loadError} Os dados abaixo são da última consulta bem-sucedida.</div>}
  <p className="footnote">Tarefas compartilhadas · automação de gestão e WhatsApp ainda não conectados. Agente configurado não significa agente em execução.</p>
  {decision&&<form className="panel" onSubmit={saveDecision}><h2>{decision.action}: {decision.task.titulo}</h2><label>Motivo da decisão<textarea required minLength={3} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy} className="primary">Registrar decisão</button> <button type="button" disabled={busy} onClick={()=>setDecision(null)}>Cancelar</button></form>}
  <section className="management-hero"><div><p className="eyebrow">COO DIGITAL · MODO GESTÃO</p><h1>Operação com dado real,<br/>não demonstração.</h1><p>Briefing, prioridades e decisões compartilhadas pela equipe.</p></div><div className={'agent-status '+(data?.agente?.ativo?'online':'offline')}><span></span><strong>{data?.agente?.ativo?'Agente configurado':'Agente indisponível'}</strong><small>{data?.agente?`v${data.agente.versao} · atualizado ${new Date(data.agente.atualizado_em).toLocaleString('pt-BR')}`:'Configuração não encontrada'}</small></div></section>
  <section className="management-grid">
   <article className="panel management-brief"><p className="eyebrow">BRIEFING DA SESSÃO</p><h2>Até 3 prioridades</h2>{briefing.length?briefing.map((t,i)=><div className="brief-row" key={t.id}><b>0{i+1}</b><div><strong>{t.titulo}</strong><small>{t.categoria} · {fronts[t.frente]} · {ptDate(t.prazo)}</small></div></div>):<div className="empty"><h3>Nenhuma prioridade cadastrada.</h3><p>O painel não inventa tarefas. Registre abaixo o que precisa entrar no briefing.</p></div>}
   </article>
   <article className="panel management-summary"><p className="eyebrow">VISÃO OPERACIONAL</p><div className="summary-number">{tasks.filter(t=>t.status==='pendente').length}</div><strong>pendentes</strong><p>{tasks.filter(t=>t.prazo&&t.prazo<=today&&t.status==='pendente').length} vencendo hoje ou atrasadas</p><p>{tasks.filter(t=>t.status==='concluida').length} concluídas com registro</p><button disabled={busy} onClick={()=>run(load)}>Atualizar do servidor</button></article>
  </section>
  <section className="panel"><div className="queue-head"><div><p className="eyebrow">ESTEIRA COMPARTILHADA</p><h2>Tarefas da operação</h2></div></div>
   <div className="task-board">{['pendente','adiada','concluida'].map(status=><div className="task-column" key={status}><h3>{status==='pendente'?'Em andamento':status==='adiada'?'Adiada':'Concluída'} <span>{tasks.filter(t=>t.status===status).length}</span></h3>{tasks.filter(t=>t.status===status).map(t=><article className="task-card" key={t.id}><small>{t.categoria} · {fronts[t.frente]}</small><strong>{t.titulo}</strong>{t.cliente&&<p>{t.cliente}</p>}<p className="footnote">{ptDate(t.prazo)}{t.prioridade?' · prioridade':''}</p>{canWrite&&<div className="task-actions">{status!=='concluida'&&<button onClick={()=>change(t,'concluir')}>Concluir</button>}{status==='pendente'&&<button onClick={()=>change(t,'adiar')}>Adiar</button>}{status!=='pendente'&&<button onClick={()=>change(t,'reabrir')}>Reabrir</button>}</div>}</article>)}{!tasks.some(t=>t.status===status)&&<p className="footnote">Nenhuma tarefa neste estado.</p>}</div>)}</div>
  </section>
  {canWrite&&<form className="panel management-form" onSubmit={create}><p className="eyebrow">NOVA TAREFA REAL</p><h2>Adicionar à rotina compartilhada</h2><label>Tarefa<input value={form.titulo} required minLength="3" maxLength="300" onChange={e=>setForm({...form,titulo:e.target.value})}/></label><div className="form-four"><label>Categoria<select value={form.categoria} onChange={e=>setForm({...form,categoria:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Frente<select value={form.frente} onChange={e=>setForm({...form,frente:e.target.value})}>{Object.entries(fronts).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Cliente (opcional)<input value={form.cliente} onChange={e=>setForm({...form,cliente:e.target.value})}/></label><label>Prazo<input type="date" value={form.prazo} onChange={e=>setForm({...form,prazo:e.target.value})}/></label></div><label className="check"><input type="checkbox" checked={form.prioridade} onChange={e=>setForm({...form,prioridade:e.target.checked})}/>Incluir entre as prioridades do briefing</label><label>Justificativa<textarea value={note} required minLength="3" onChange={e=>setNote(e.target.value)} placeholder="Por que esta tarefa deve entrar agora?"/></label><button className="primary" disabled={busy}>Registrar tarefa</button></form>}
  <p className="footnote management-note">Esta primeira versão não envia mensagens, não publica e não altera campanhas. Esses atos continuam dependendo de aprovação explícita.</p>
 </div>
}
